<?php


/**
 * This class adds structure of 'linkedin_token' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Dec  9 12:32:36 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfLinkedInPlugin.lib.model.map
 */
class sfLinkedInTokenMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfLinkedInPlugin.lib.model.map.sfLinkedInTokenMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfLinkedInTokenPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfLinkedInTokenPeer::TABLE_NAME);
		$tMap->setPhpName('sfLinkedInToken');
		$tMap->setClassname('sfLinkedInToken');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', false, 255);

		$tMap->addColumn('TOKEN_KEY', 'TokenKey', 'CLOB', false, null);

		$tMap->addColumn('TOKEN_SECRET', 'TokenSecret', 'CLOB', false, null);

		$tMap->addForeignPrimaryKey('USER_ID', 'UserId', 'INTEGER' , 'member', 'ID', true, null);

		$tMap->addColumn('EXPIRE_IN', 'ExpireIn', 'INTEGER', false, null);

		$tMap->addColumn('IDENTIFIER', 'Identifier', 'VARCHAR', false, 255);

		$tMap->addColumn('STATUS', 'Status', 'VARCHAR', false, 255);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // sfLinkedInTokenMapBuilder
